language: rust
os:
  - linux
  - osx
  - windows
cache: cargo
before_install:
    - cd encoder
script:
  - cargo test --lib --locked
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check
  - cargo build --release
before_deploy:
  - git config --local user.name "Peter Smith"
  - git config --local user.email "peter@orukusaki.co.uk"
  - name="hex2wav-$TRAVIS_TAG-$TRAVIS_OS_NAME"
  - mkdir $name
  - cp target/$TARGET/release/hex2wav $name/
  - cp ../README.md ../LICENSE $name/
  - tar czvf $name.tar.gz $name
deploy:
  provider: releases
  file: hex2wav-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz
  cleanup: false
  on:
    branch: main
    tags: true
  token:
    secure: pUzxcoDLCkBk2yIjqxy3wNyOEcZ2XUllQndfVMWvnea8yRnfpDT0EtWakIvvqqWzNQ7W7hSYE4sosO7fZZVnawk5FxsYI0o7GUSy3f9AbmUZgIuUmQcSluJD62R064vWQMReZ1MGTE/PlyYoHLu2YDMqznD8uQ2RTVLaBAE4SFxoj6gVrmydzYZqhezvZAHR8ji/U5oUaBM1rr+FuNutXH3tl3Ew2P7lla5P4RL89Nr9NKgu76qLCI72Z0BgzeH37bE3pPr0RlEifQidK/PNrNFnF/BOmBJhz+iLP8XzJGENUJMlVd7wXYd1tW0SABLOBhwP/1GH/Rg5lbV/8OhKWyNzu5PH5fHAXVA1bs6jAPj6DsJ0PAq/gPOZRAH8ATxdy8sdTZ9YgNZp/s6qslzoag3G7hOuvObFdI1ERj7yo36SirGo+r3bUW1RxmgFNUf/G/e5LUlusfLoIOQwhM9R8L98GtVGCqrYPLyst91pJ60DAQ7Y/lurASeawE0e2A+XPHddUwXfgVRUzohgzmABT59y8xfQT2ROBZBTDfYSbHXBzO4XOxsoDx0jPvN2FhDoI/WmXVj+sloLka9nB08XtKmryK4AklfV6f2q3hTqGuP8AZFNVwY2vlKPRiSsA1mnp8cbKIyw7PJZbSsCdK0F51umvWCnyKGkRKktiYINC14=

jobs:
  include:
    - language: python
      python:
          - "3.9"
      cache:
        directories:
          - "~/.platformio"
          - $HOME/.cache/pip
      before_install:
          - cd bootloader
      install:
          - pip install -U platformio
          - pio update
      script:
          - pio run
          - pio check
      before_deploy:
        - git config --local user.name "Peter Smith"
        - git config --local user.email "peter@orukusaki.co.uk"
        - name="bootloader-$TRAVIS_TAG"
        - mkdir $name
        - cp .pio/build/atmega328p/firmware.hex $name/
        - cp .pio/build/atmega328p/firmware.elf $name/
        - cp ../README.md ../LICENSE $name/
        - tar czvf $name.tar.gz $name
      deploy:
        provider: releases
        file: bootloader-$TRAVIS_TAG.tar.gz
        cleanup: false
        on:
          branch: main
          tags: true
        token:
          secure: pUzxcoDLCkBk2yIjqxy3wNyOEcZ2XUllQndfVMWvnea8yRnfpDT0EtWakIvvqqWzNQ7W7hSYE4sosO7fZZVnawk5FxsYI0o7GUSy3f9AbmUZgIuUmQcSluJD62R064vWQMReZ1MGTE/PlyYoHLu2YDMqznD8uQ2RTVLaBAE4SFxoj6gVrmydzYZqhezvZAHR8ji/U5oUaBM1rr+FuNutXH3tl3Ew2P7lla5P4RL89Nr9NKgu76qLCI72Z0BgzeH37bE3pPr0RlEifQidK/PNrNFnF/BOmBJhz+iLP8XzJGENUJMlVd7wXYd1tW0SABLOBhwP/1GH/Rg5lbV/8OhKWyNzu5PH5fHAXVA1bs6jAPj6DsJ0PAq/gPOZRAH8ATxdy8sdTZ9YgNZp/s6qslzoag3G7hOuvObFdI1ERj7yo36SirGo+r3bUW1RxmgFNUf/G/e5LUlusfLoIOQwhM9R8L98GtVGCqrYPLyst91pJ60DAQ7Y/lurASeawE0e2A+XPHddUwXfgVRUzohgzmABT59y8xfQT2ROBZBTDfYSbHXBzO4XOxsoDx0jPvN2FhDoI/WmXVj+sloLka9nB08XtKmryK4AklfV6f2q3hTqGuP8AZFNVwY2vlKPRiSsA1mnp8cbKIyw7PJZbSsCdK0F51umvWCnyKGkRKktiYINC14=
