[build]
target = "avr-unknown-gnu-atmega328"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno --open-console --baudrate 57600"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]